name: electronic_document_management_backend
description: A server app for school electronic document management.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  json_annotation: ^4.8.0
  uuid: ^4.0.0
  logging: ^1.2.0
  dotenv: ^4.2.0
  mongo_dart: ^0.10.6
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  test: ^1.24.0

